"""Testes do adaptador SQLite → PostgreSQL (tradução de consultas)."""

import unittest

from sistema import bancodados


class TestTraducao(unittest.TestCase):
    def test_placeholders_viram_psycopg(self):
        self.assertEqual(
            bancodados.traduzir_sql("SELECT * FROM x WHERE a = ? AND b = ?"),
            "SELECT * FROM x WHERE a = %s AND b = %s")

    def test_interrogacao_dentro_de_aspas_preservada(self):
        self.assertEqual(
            bancodados.traduzir_sql("SELECT '?' FROM x WHERE a = ?"),
            "SELECT '?' FROM x WHERE a = %s")

    def test_percentual_literal_escapado(self):
        # LIKE 'Gabinete do(a)%' precisa virar %% para o psycopg2.
        self.assertEqual(
            bancodados.traduzir_sql("WHERE nome LIKE 'Gabinete do(a)%'"),
            "WHERE nome LIKE 'Gabinete do(a)%%'")

    def test_insert_ganha_returning_id(self):
        sql = bancodados.com_returning(
            "INSERT INTO processo (numero, ano) VALUES (%s, %s)")
        self.assertTrue(sql.endswith("RETURNING id"))

    def test_insert_em_tabela_sem_id_nao_ganha_returning(self):
        for tabela in ("unidade_area", "unidade_acao", "simbolo", "rubrica"):
            sql = bancodados.com_returning(
                f"INSERT INTO {tabela} (a) VALUES (%s)")
            self.assertNotIn("RETURNING", sql)

    def test_select_nao_ganha_returning(self):
        sql = bancodados.com_returning("SELECT id FROM processo")
        self.assertNotIn("RETURNING", sql)

    def test_schema_convertido_para_identity(self):
        convertido = bancodados.schema_para_postgres(
            "CREATE TABLE x (id INTEGER PRIMARY KEY, nome TEXT);")
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", convertido)
        self.assertNotIn("INTEGER PRIMARY KEY,", convertido)

    def test_deteccao_de_url_postgres(self):
        self.assertTrue(bancodados.eh_url_postgres("postgresql://u:p@h/db"))
        self.assertTrue(bancodados.eh_url_postgres("postgres://u:p@h/db"))
        self.assertFalse(bancodados.eh_url_postgres("cmdc.db"))
        self.assertFalse(bancodados.eh_url_postgres(":memory:"))


if __name__ == "__main__":
    unittest.main()
