"""Adaptador de banco: SQLite (local/testes) e PostgreSQL/Supabase (produção).

Todo o sistema fala o dialeto do sqlite3 (placeholders `?`, `lastrowid`,
`executescript`). Este módulo permite apontar a MESMA base de código para
um PostgreSQL (ex.: Supabase) via `DATABASE_URL`, traduzindo em tempo de
execução:

- `?`  → `%s` (fora de aspas) e `%` literal → `%%`;
- INSERTs ganham `RETURNING id` para alimentar `lastrowid` (exceto tabelas
  sem coluna id);
- `executescript` roda o texto puro (schema/seed, sem tradução);
- erros de integridade do psycopg2 são re-erguidos como
  `sqlite3.IntegrityError`, que é o que a API trata.

O schema é convertido trocando `INTEGER PRIMARY KEY` (autoincremento do
SQLite) por coluna IDENTITY do PostgreSQL; após o seed (que fixa ids
explícitos), as sequências são realinhadas com `setval`.
"""

from __future__ import annotations

import re
import sqlite3

# Tabelas sem coluna `id` (chave composta) — não recebem RETURNING id.
_TABELAS_SEM_ID = {"unidade_area", "unidade_acao", "simbolo", "rubrica"}

_INSERT_RE = re.compile(r"^\s*INSERT\s+INTO\s+([\"a-zA-Z_][\"\w]*)",
                        re.IGNORECASE)


def eh_url_postgres(caminho: str) -> bool:
    return str(caminho).startswith(("postgres://", "postgresql://"))


def traduzir_sql(sql: str) -> str:
    """Traduz uma consulta do dialeto sqlite3 para psycopg2.

    Troca `?` por `%s` fora de literais de texto e escapa `%` (o psycopg2
    interpreta `%` quando há parâmetros).
    """
    saida = []
    em_aspas = False
    for ch in sql:
        if ch == "'":
            em_aspas = not em_aspas
            saida.append(ch)
        elif ch == "?" and not em_aspas:
            saida.append("%s")
        elif ch == "%":
            saida.append("%%")
        else:
            saida.append(ch)
    return "".join(saida)


def com_returning(sql: str) -> str:
    """Anexa RETURNING id aos INSERTs de tabelas com id (para lastrowid)."""
    m = _INSERT_RE.match(sql)
    if not m:
        return sql
    tabela = m.group(1).strip('"').lower()
    if tabela in _TABELAS_SEM_ID or "returning" in sql.lower():
        return sql
    return sql.rstrip().rstrip(";") + " RETURNING id"


def schema_para_postgres(schema_sql: str) -> str:
    """Converte o schema portável para PostgreSQL (autoincremento)."""
    return schema_sql.replace(
        "INTEGER PRIMARY KEY",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")


# Migrações idempotentes para bancos PostgreSQL JÁ CRIADOS (ex.: o Supabase
# de produção, cujo schema nasceu antes destas colunas). Num banco novo o
# schema.sql já traz tudo — os comandos abaixo viram no-op.
MIGRACOES_PG = """
ALTER TABLE proposicao ADD COLUMN IF NOT EXISTS finalidade TEXT
  CHECK (finalidade IN ('RETIRADA', 'INCLUSAO_PAUTA', 'DESARQUIVAMENTO'));
ALTER TABLE proposicao ADD COLUMN IF NOT EXISTS proposicao_alvo_id INTEGER
  REFERENCES proposicao (id);
ALTER TABLE proposicao ADD COLUMN IF NOT EXISTS despacho TEXT;
ALTER TABLE proposicao ADD COLUMN IF NOT EXISTS despacho_data TEXT;
INSERT INTO unidade_acao (unidade_id, acao)
  SELECT id, 'DESPACHAR' FROM unidade WHERE nome = 'Presidência'
  ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS recusa (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposicao_id  INTEGER NOT NULL REFERENCES proposicao (id),
    motivo         TEXT NOT NULL,
    data           TEXT NOT NULL,
    recurso_razoes TEXT,
    recurso_data   TEXT,
    decisao        TEXT CHECK (decisao IN ('PROVIDO', 'NEGADO')),
    decisao_motivo TEXT,
    decisao_data   TEXT,
    situacao       TEXT NOT NULL DEFAULT 'RECUSADA' CHECK (situacao IN
                     ('RECUSADA', 'EM_RECURSO', 'MANTIDA', 'REVERTIDA'))
);
"""

# Tabelas novas para um arquivo SQLite antigo (criadas se ausentes).
TABELAS_NOVAS_SQLITE = {
    "recusa": """
        CREATE TABLE recusa (
            id             INTEGER PRIMARY KEY,
            proposicao_id  INTEGER NOT NULL REFERENCES proposicao (id),
            motivo         TEXT NOT NULL,
            data           TEXT NOT NULL,
            recurso_razoes TEXT,
            recurso_data   TEXT,
            decisao        TEXT CHECK (decisao IN ('PROVIDO', 'NEGADO')),
            decisao_motivo TEXT,
            decisao_data   TEXT,
            situacao       TEXT NOT NULL DEFAULT 'RECUSADA' CHECK (situacao IN
                             ('RECUSADA', 'EM_RECURSO', 'MANTIDA', 'REVERTIDA'))
        )""",
}

# Mesmas migrações para um arquivo SQLite antigo (o ALTER do SQLite não
# aceita IF NOT EXISTS — quem chama confere as colunas via PRAGMA).
COLUNAS_NOVAS_PROPOSICAO = [
    ("finalidade", "TEXT CHECK (finalidade IN "
                   "('RETIRADA', 'INCLUSAO_PAUTA', 'DESARQUIVAMENTO'))"),
    ("proposicao_alvo_id", "INTEGER REFERENCES proposicao (id)"),
    ("despacho", "TEXT"),
    ("despacho_data", "TEXT"),
]


# Realinha as sequências IDENTITY após o seed (que insere ids explícitos).
SETVAL_POS_SEED = """
DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT c.table_name FROM information_schema.columns c
            WHERE c.column_name = 'id' AND c.table_schema = 'public'
  LOOP
    EXECUTE format(
      'SELECT setval(pg_get_serial_sequence(%L, %L), '
      'COALESCE((SELECT MAX(id) FROM %I), 0) + 1, false)',
      t.table_name, 'id', t.table_name);
  END LOOP;
END $$;
"""


class _CursorPG:
    """Cursor com a interface que o sistema usa (fetch*, iteração, lastrowid)."""

    def __init__(self, cursor, lastrowid=None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __iter__(self):
        return iter(self._cursor.fetchall())


class ConexaoPostgres:
    """Conexão PostgreSQL com a interface do sqlite3 usada pelo sistema."""

    def __init__(self, url: str):
        import psycopg2  # import tardio: só é preciso em produção

        self._psycopg2 = psycopg2
        self._conexao = psycopg2.connect(url)

    def execute(self, sql: str, parametros=()):  # noqa: A003
        cursor = self._conexao.cursor()
        traduzido = com_returning(traduzir_sql(sql))
        try:
            cursor.execute(traduzido, tuple(parametros))
        except self._psycopg2.IntegrityError as erro:
            raise sqlite3.IntegrityError(str(erro).strip()) from erro
        lastrowid = None
        if traduzido.rstrip().upper().endswith("RETURNING ID"):
            linha = cursor.fetchone()
            lastrowid = linha[0] if linha else None
        return _CursorPG(cursor, lastrowid)

    def executemany(self, sql: str, seq_parametros):
        cursor = self._conexao.cursor()
        try:
            cursor.executemany(traduzir_sql(sql),
                               [tuple(p) for p in seq_parametros])
        except self._psycopg2.IntegrityError as erro:
            raise sqlite3.IntegrityError(str(erro).strip()) from erro
        return _CursorPG(cursor)

    def executescript(self, script: str):
        # Texto puro (schema/seed): sem parâmetros, sem tradução de `%`.
        cursor = self._conexao.cursor()
        cursor.execute(script)
        return _CursorPG(cursor)

    def commit(self):
        self._conexao.commit()

    def rollback(self):
        self._conexao.rollback()

    def close(self):
        self._conexao.close()
