-- Seed gerado por sistema/gerar_seed.py a partir de orgao/cmdc.py
-- Fonte: Lei nº 3.525/2025 (estrutura e Anexo I)

INSERT INTO norma (id, especie, numero, ementa) VALUES
  (1, 'Lei', '3.525/2025', 'Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências');

INSERT INTO unidade (id, nome, sigla, grau, tipo, unidade_pai_id, norma_id, vigente_desde) VALUES
  (1, 'Mesa Diretora', 'MESA', NULL, 'POLITICO', NULL, 1, '2025-09-01'),
  (2, 'Presidência', 'PRES', NULL, 'POLITICO', 1, 1, '2025-09-01'),
  (3, 'Gabinetes de Vereadores', 'GAB', NULL, 'POLITICO', 1, 1, '2025-09-01'),
  (4, 'Comissão Permanente de Licitação', NULL, NULL, 'COMISSAO', 1, 1, '2025-09-01'),
  (5, 'Comissão Permanente de Recebimento Definitivo de Obras, Serviços e Bens', NULL, NULL, 'COMISSAO', 1, 1, '2025-09-01'),
  (6, 'Comissão Permanente de Aplicação de Sanções', NULL, NULL, 'COMISSAO', 1, 1, '2025-09-01'),
  (7, 'Comissão Permanente de Proteção de Dados Pessoais', NULL, NULL, 'COMISSAO', 1, 1, '2025-09-01'),
  (8, 'Comissão Permanente de Atualização e Consolidação de Leis e Normas Municipais', NULL, NULL, 'COMISSAO', 1, 1, '2025-09-01'),
  (9, 'Consultoria-Geral Legislativa', 'CGL', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (10, 'Controladoria-Geral', 'CG', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (11, 'Diretoria da Escola do Legislativo', 'DEL', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (12, 'Diretoria de Plenário', 'DP', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (13, 'Ouvidoria-Geral', 'OG', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (14, 'Procuradoria-Geral', 'PG', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (15, 'Superintendência-Geral', 'SG', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (16, 'Superintendência de Assuntos Estratégicos', 'SAE', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (17, 'Diretoria-Geral', 'DG', 1, 'SUPERIOR', 2, 1, '2025-09-01'),
  (18, 'Assessoria de Gabinete Parlamentar', NULL, 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (19, 'Assessoria Especial da Presidência', NULL, 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (20, 'Assessores Parlamentares', NULL, 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (21, 'Assistência às Comissões Permanentes', NULL, 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (22, 'Coordenadoria de Apoio Legislativo', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (23, 'Coordenadoria de Assuntos de Plenário', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (24, 'Coordenadoria de Atas e Projetos', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (25, 'Coordenadoria de Avaliação e Acompanhamento de Compras', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (26, 'Coordenadoria de Cerimonial e Comunicação Social', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (27, 'Coordenadoria de Contabilidade', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (28, 'Coordenadoria de Documentação Histórica', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (29, 'Coordenadoria de Finanças', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (30, 'Coordenadoria de Licitações e Contratos', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (31, 'Coordenadoria de Manutenção', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (32, 'Coordenadoria de Material', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (33, 'Coordenadoria de Patrimônio', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (34, 'Coordenadoria de Polícia Legislativa', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (35, 'Coordenadoria de Prevenção a Incêndio', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (36, 'Coordenadoria de Publicações e Transparência', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (37, 'Coordenadoria de Redação Oficial e Legislativa', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (38, 'Coordenadoria de Recursos Humanos', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (39, 'Coordenadoria de Tecnologia da Informação e Comunicação', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (40, 'Coordenadoria da Secretaria-Geral', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (41, 'Diretoria Administrativa', NULL, 2, 'COORDENADORIA', 17, 1, '2025-09-01'),
  (42, 'Departamento do e-Social', NULL, 4, 'AUXILIAR', 41, 1, '2025-09-01'),
  (43, 'Serviços de Copa', NULL, 4, 'AUXILIAR', 41, 1, '2025-09-01'),
  (44, 'Manutenção Predial', NULL, 4, 'AUXILIAR', 41, 1, '2025-09-01'),
  (45, 'Telefonia', NULL, 4, 'AUXILIAR', 41, 1, '2025-09-01'),
  (46, 'Reprografia', NULL, 4, 'AUXILIAR', 41, 1, '2025-09-01'),
  (47, 'Limpeza', NULL, 4, 'AUXILIAR', 41, 1, '2025-09-01'),
  (48, 'Transporte', NULL, 4, 'AUXILIAR', 41, 1, '2025-09-01'),
  (49, 'Vigilância Patrimonial', NULL, 4, 'AUXILIAR', 41, 1, '2025-09-01'),
  (50, 'Gabinete do(a) Vereador(a) Chiquinho Caipira', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (51, 'Gabinete do(a) Vereador(a) Alex Freitas', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (52, 'Gabinete do(a) Vereador(a) Andréia Zito', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (53, 'Gabinete do(a) Vereador(a) Junior Uios', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (54, 'Gabinete do(a) Vereador(a) Carlinhos da Barreira', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (55, 'Gabinete do(a) Vereador(a) Claudio Thomaz', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (56, 'Gabinete do(a) Vereador(a) Clovinho Sempre Junto', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (57, 'Gabinete do(a) Vereador(a) Delza de Oliveira', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (58, 'Gabinete do(a) Vereador(a) Junior Reis', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (59, 'Gabinete do(a) Vereador(a) Anderson Lopes', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (60, 'Gabinete do(a) Vereador(a) Eduardo Moreira', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (61, 'Gabinete do(a) Vereador(a) Fernanda Costa', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (62, 'Gabinete do(a) Vereador(a) Giorgio Monteiro', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (63, 'Gabinete do(a) Vereador(a) Juliana do Taxi', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (64, 'Gabinete do(a) Vereador(a) Leandro Enfermeiro', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (65, 'Gabinete do(a) Vereador(a) Catiti', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (66, 'Gabinete do(a) Vereador(a) Marquinho Oi', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (67, 'Gabinete do(a) Vereador(a) Marquinho Dentista', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (68, 'Gabinete do(a) Vereador(a) Marquinho da Pipa', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (69, 'Gabinete do(a) Vereador(a) Dr. Maurício', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (70, 'Gabinete do(a) Vereador(a) Michel Reis', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (71, 'Gabinete do(a) Vereador(a) Michele Tavares', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (72, 'Gabinete do(a) Vereador(a) Moises Neguinho', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (73, 'Gabinete do(a) Vereador(a) Beto Gabriel', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (74, 'Gabinete do(a) Vereador(a) Saulo Henrique', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (75, 'Gabinete do(a) Vereador(a) Serginho Corrêa', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (76, 'Gabinete do(a) Vereador(a) Valdecy Nunes', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (77, 'Gabinete do(a) Vereador(a) Vitinho Grandão', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01'),
  (78, 'Gabinete do(a) Vereador(a) Wendell Oliveira', 'GAB', 3, 'ASSESSORAMENTO', 3, 1, '2025-09-01');

INSERT INTO competencia (unidade_id, descricao, base_legal) VALUES
  (1, 'Comando político-institucional da Casa; não integra a hierarquia técnico-administrativa (art. 2º, parágrafo único)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (2, 'Dirigir os trabalhos legislativos e administrativos', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (4, 'Órgão colegiado de apoio à administração; membros com gratificação de 40% (art. 46, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (5, 'Órgão colegiado de apoio à administração; membros com gratificação de 40% (art. 46, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (6, 'Órgão colegiado de apoio à administração; membros com gratificação de 40% (art. 46, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (7, 'Órgão colegiado de apoio à administração; membros com gratificação de 40% (art. 46, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (8, 'Órgão colegiado de apoio à administração; membros com gratificação de 40% (art. 46, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (9, 'Consultoria e assessoramento técnico-legislativo (art. 11)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (10, 'Controle interno, auditoria e fiscalização (art. 12)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (11, 'Formação e capacitação legislativa (art. 13)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (12, 'Organização dos trabalhos e da ordem do dia do Plenário (art. 14)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (13, 'Ouvidoria: recebimento e encaminhamento de demandas (art. 18)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (14, 'Representação e consultoria jurídica da Câmara (art. 19)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (15, 'Superintendência dos serviços administrativos (art. 16)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (16, 'Planejamento e assuntos estratégicos (art. 17)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (17, 'Órgão central de apoio administrativo, diretamente subordinado à Presidência; supervisiona telefonia e transporte (art. 15)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (18, 'Assessoramento parlamentar (3º grau); provimento por indicação dos titulares (art. 3º, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (19, 'Assessoramento parlamentar (3º grau); provimento por indicação dos titulares (art. 3º, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (20, 'Assessoramento parlamentar (3º grau); provimento por indicação dos titulares (art. 3º, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (21, 'Assessoramento parlamentar (3º grau); provimento por indicação dos titulares (art. 3º, §2º)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (22, 'Apoio ao processo legislativo e às sessões plenárias (art. 20)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (23, 'Suporte à ordem do dia e aos trabalhos de Plenário (art. 21)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (24, 'Elaboração de atas das sessões e autuação de projetos e proposições (art. 22)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (25, 'Fiscalização e acompanhamento das aquisições e contratações (art. 23)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (26, 'Cerimonial, comunicação institucional e imprensa (art. 24)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (27, 'Escrituração contábil, empenho e execução orçamentária (art. 25)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (28, 'Guarda e preservação do acervo documental e histórico (art. 26)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (29, 'Gestão financeira, pagamentos e conciliação (art. 27)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (30, 'Formalização e gestão de licitações e contratos, Lei 14.133/2021 (art. 28)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (31, 'Manutenção predial e das instalações; serviços de copa, limpeza e reprografia (art. 29)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (32, 'Gestão de material e almoxarifado; termo de referência e pesquisa de preços (art. 30)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (33, 'Registro, controle e baixa dos bens patrimoniais (art. 31)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (34, 'Segurança institucional, poder de polícia e fiscalização da vigilância (art. 32)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (35, 'Prevenção e combate a incêndio e segurança predial (art. 33)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (36, 'Publicação oficial dos atos e transparência ativa, LAI (art. 34)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (37, 'Redação final de autógrafos, leis e atos normativos (art. 35)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (38, 'Gestão de pessoal: cadastro, provimento, lotação e vida funcional dos servidores (art. 36)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (39, 'Gestão dos sistemas e da infraestrutura de tecnologia da informação (art. 38)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (40, 'Protocolo-geral, autuação, numeração e tramitação de processos administrativos e legislativos (art. 37)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (41, 'Coordenação dos serviços administrativos e auxiliares (art. 39)', 'Lei 3.525/2025 — Dispõe sobre a organização administrativa da Câmara Municipal de Duque de Caxias, e dá outras providências'),
  (50, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (51, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (52, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (53, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (54, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (55, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (56, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (57, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (58, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (59, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (60, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (61, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (62, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (63, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (64, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (65, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (66, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (67, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (68, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (69, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (70, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (71, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (72, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (73, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (74, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (75, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (76, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (77, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025'),
  (78, 'Assessoramento político-legislativo ao titular do mandato; autoria e apresentação de proposições (art. 1º, p.u., e art. 79)', 'Lei 3.525/2025');

INSERT INTO simbolo (codigo, retribuicao_base, natureza) VALUES
  ('ASS-1', 6870, 'COMISSAO'),
  ('ASS-10', 3000, 'COMISSAO'),
  ('ASS-11', 1560, 'COMISSAO'),
  ('ASS-12', 6870, 'COMISSAO'),
  ('ASS-13', 4125, 'COMISSAO'),
  ('ASS-3', 6870, 'COMISSAO'),
  ('ASS-5', 4125, 'COMISSAO'),
  ('ASS-6', 4125, 'COMISSAO'),
  ('ASS-7', 4125, 'COMISSAO'),
  ('ASS-8', 6870, 'COMISSAO'),
  ('ASS-9', 4125, 'COMISSAO'),
  ('CAE-1', 6870, 'COMISSAO'),
  ('DAS-8', 15925, 'COMISSAO'),
  ('FC-1', 15925, 'FUNCAO_CONFIANCA'),
  ('FC-2', 6870, 'FUNCAO_CONFIANCA'),
  ('GAB-1', 6870, 'COMISSAO'),
  ('GAB-3', 6870, 'COMISSAO'),
  ('PAR-1', 6870, 'COMISSAO'),
  ('PAR-2', 6870, 'COMISSAO'),
  ('PAR-3', 6870, 'COMISSAO'),
  ('SAS-6', 12250, 'COMISSAO'),
  ('SL-1', 10125, 'COMISSAO');

INSERT INTO cargo (id, denominacao, tipo, simbolo_codigo, quantidade_vagas, unidade_lotacao_id, norma_id) VALUES
  (1, 'Assessor de Assuntos Especiais', 'COMISSAO', 'DAS-8', 1, NULL, 1),
  (2, 'Controlador-Geral', 'FUNCAO_CONFIANCA', 'FC-1', 1, 10, 1),
  (3, 'Diretor da Escola do Legislativo', 'COMISSAO', 'DAS-8', 1, 11, 1),
  (4, 'Diretor-Geral', 'COMISSAO', 'DAS-8', 1, 17, 1),
  (5, 'Diretor de Plenário', 'COMISSAO', 'DAS-8', 1, 12, 1),
  (6, 'Consultor-Geral Legislativo', 'COMISSAO', 'DAS-8', 1, 9, 1),
  (7, 'Consultor Especial das Comissões Técnicas', 'COMISSAO', 'DAS-8', 1, NULL, 1),
  (8, 'Procurador-Geral', 'COMISSAO', 'DAS-8', 1, 14, 1),
  (9, 'Superintendente-Geral', 'COMISSAO', 'DAS-8', 1, 15, 1),
  (10, 'Superintendente de Assuntos Estratégicos', 'COMISSAO', 'SAS-6', 1, 16, 1),
  (11, 'Ouvidor-Geral', 'COMISSAO', 'CAE-1', 1, 13, 1),
  (12, 'Secretário Legislativo', 'COMISSAO', 'SL-1', 29, NULL, 1),
  (13, 'Assessor de Mediação de Conflitos', 'COMISSAO', 'ASS-1', 1, NULL, 1),
  (14, 'Assessor Parlamentar I', 'COMISSAO', 'PAR-3', 96, NULL, 1),
  (15, 'Assessor Parlamentar II', 'COMISSAO', 'PAR-2', 96, NULL, 1),
  (16, 'Assistente do Cerimonial e Comunicação', 'COMISSAO', 'ASS-3', 1, NULL, 1),
  (17, 'Assistente do Presidente', 'COMISSAO', 'GAB-3', 4, NULL, 1),
  (18, 'Chefe de Gabinete', 'COMISSAO', 'GAB-1', 29, NULL, 1),
  (19, 'Assessor de Comissão Legislativa e Parlamentar', 'COMISSAO', 'ASS-1', 31, NULL, 1),
  (20, 'Assessor Parlamentar III', 'COMISSAO', 'PAR-1', 70, NULL, 1),
  (21, 'Coord. de Apoio Legislativo', 'FUNCAO_CONFIANCA', 'FC-2', 1, 22, 1),
  (22, 'Coord. de Assuntos de Plenário', 'FUNCAO_CONFIANCA', 'FC-2', 1, 23, 1),
  (23, 'Coord. de Atas e Projetos', 'FUNCAO_CONFIANCA', 'FC-2', 1, 24, 1),
  (24, 'Coord. de Avaliação e Acompanhamento de Compras', 'COMISSAO', 'CAE-1', 1, 25, 1),
  (25, 'Coord. de Contabilidade', 'FUNCAO_CONFIANCA', 'FC-2', 1, 27, 1),
  (26, 'Coord. de Documentação Histórica', 'COMISSAO', 'CAE-1', 1, 28, 1),
  (27, 'Coord. de Finanças', 'COMISSAO', 'CAE-1', 1, 29, 1),
  (28, 'Coord. de Cerimonial e Comunicação Social', 'COMISSAO', 'CAE-1', 1, 26, 1),
  (29, 'Coord. de Licitações e Contratos', 'COMISSAO', 'CAE-1', 1, 30, 1),
  (30, 'Coord. de Manutenção', 'FUNCAO_CONFIANCA', 'FC-2', 1, 31, 1),
  (31, 'Coord. de Material', 'FUNCAO_CONFIANCA', 'FC-2', 1, 32, 1),
  (32, 'Coord. de Patrimônio', 'FUNCAO_CONFIANCA', 'FC-2', 1, 33, 1),
  (33, 'Coord. de Polícia Legislativa', 'FUNCAO_CONFIANCA', 'FC-2', 1, 34, 1),
  (34, 'Coord. de Prevenção a Incêndio', 'FUNCAO_CONFIANCA', 'FC-2', 1, 35, 1),
  (35, 'Coord. de Publicações e Transparência', 'COMISSAO', 'CAE-1', 1, 36, 1),
  (36, 'Coord. de Redação Oficial e Legislativa', 'FUNCAO_CONFIANCA', 'FC-2', 1, 37, 1),
  (37, 'Coord. de Recursos Humanos', 'COMISSAO', 'CAE-1', 1, 38, 1),
  (38, 'Coord. de Tecnologia da Informação e Comunicação', 'FUNCAO_CONFIANCA', 'FC-2', 1, 39, 1),
  (39, 'Coord. da Secretaria-Geral', 'FUNCAO_CONFIANCA', 'FC-2', 1, 40, 1),
  (40, 'Diretor Administrativo', 'COMISSAO', 'CAE-1', 1, 41, 1),
  (41, 'Assistente das Comissões Permanentes', 'COMISSAO', 'ASS-5', 33, NULL, 1),
  (42, 'Assessor de Plenário', 'COMISSAO', 'ASS-6', 29, NULL, 1),
  (43, 'Assistente do 1º Secretário', 'COMISSAO', 'ASS-7', 1, NULL, 1),
  (44, 'Assistente do Diretor I', 'COMISSAO', 'ASS-8', 1, NULL, 1),
  (45, 'Assistente do Diretor II', 'COMISSAO', 'ASS-9', 1, NULL, 1),
  (46, 'Assistente de Gabinete I', 'COMISSAO', 'ASS-10', 90, NULL, 1),
  (47, 'Assistente de Gabinete II', 'COMISSAO', 'ASS-11', 70, NULL, 1),
  (48, 'Assessor de Coordenadoria', 'COMISSAO', 'ASS-12', 1, NULL, 1),
  (49, 'Assistente da Coordenadoria', 'COMISSAO', 'ASS-13', 1, NULL, 1);

INSERT INTO rubrica (codigo, descricao, natureza, base_legal, percentual_max, incorporavel) VALUES
  ('VENC', 'Vencimento/retribuição básica', 'VENCIMENTO', 'Lei 3.525/2025, art. 6º', NULL, 1),
  ('GAL', 'Gratificação de Atividade Legislativa', 'GRATIFICACAO', 'Lei 3.525/2025, art. 7º', 150, 0),
  ('REP-TL', 'Representação — carreira de Técnico Legislativo', 'ADICIONAL', 'Lei 3.525/2025, art. 8º', 60, 0),
  ('GAP', 'Gratificação de Atividade Perigosa', 'GRATIFICACAO', 'Lei 3.525/2025, art. 9º', 40, 0),
  ('REP-JUD', 'Adicional de Representação Judiciária', 'ADICIONAL', 'Lei 3.525/2025, art. 10', 40, 0),
  ('GRAT-COM', 'Gratificação de comissão (indenizatória, não incorporável)', 'GRATIFICACAO', 'Lei 3.525/2025, arts. 46-47', 40, 0),
  ('GRAT-CC', 'Gratificação de efetivo nomeado em cargo em comissão', 'GRATIFICACAO', 'Lei 3.525/2025, art. 3º, §4º', 100, 0),
  ('ATS', 'Adicional por tempo de serviço (triênio)', 'ADICIONAL', 'Lei 3.525/2025, art. 6º, §2º, III', NULL, 1),
  ('AD-PROD', 'Adicional de Produtividade (por conceito da avaliação)', 'ADICIONAL', 'Lei 3.226/2022, art. 14', 70, 0),
  ('IND-GAB', 'Indenização de Representação de Gabinete Avançado', 'ADICIONAL', 'Lei 3.226/2022, art. 13', 70, 0),
  ('AUX-ALIM', 'Auxílio-alimentação (valor fixado por ato do Presidente)', 'ADICIONAL', 'Lei 3.226/2022, art. 17; Lei 3.525/2025, art. 4º', NULL, 0),
  ('AUX-REF', 'Auxílio-refeição (valor fixado por ato do Presidente)', 'ADICIONAL', 'Lei 3.226/2022, art. 17; Lei 3.525/2025, art. 4º', NULL, 0),
  ('AUX-LOC', 'Auxílio-locomoção (valor fixado por ato do Presidente)', 'ADICIONAL', 'Lei 3.226/2022, art. 17; Lei 3.525/2025, art. 4º', NULL, 0);

INSERT INTO comissao_permanente (id, nome) VALUES
  (1, 'Comissão de Legislação, Justiça e Redação Final'),
  (2, 'Comissão de Finanças e Orçamento'),
  (3, 'Comissão de Educação e Cultura'),
  (4, 'Comissão de Saúde e Assistência Social'),
  (5, 'Comissão de Transportes'),
  (6, 'Comissão de Defesa do Consumidor'),
  (7, 'Comissão de Obras e Serviços Públicos'),
  (8, 'Comissão de Meio Ambiente e Qualidade de Vida'),
  (9, 'Comissão de Fiscalização'),
  (10, 'Comissão de Desenvolvimento Urbano'),
  (11, 'Comissão dos Direitos da Mulher e da Criança e Adolescente'),
  (12, 'Comissão da Defesa dos Direitos Humanos'),
  (13, 'Comissão de Defesa dos Portadores de Necessidades Especiais'),
  (14, 'Comissão de Segurança Alimentar e Nutricional'),
  (15, 'Comissão de Segurança'),
  (16, 'Comissão de Esporte, Lazer e Turismo'),
  (17, 'Comissão de Prevenção e Combate às Drogas'),
  (18, 'Comissão de Prevenção e Combate à Pirataria'),
  (19, 'Comissão de Defesa dos Direitos dos Idosos'),
  (20, 'Comissão de Defesa dos Direitos da Juventude');

INSERT INTO tipo_processo (id, codigo, nome, dominio) VALUES
  (1, 'PL', 'Projeto de Lei', 'LEGISLATIVO'),
  (2, 'COMPRA', 'Contratação (Lei 14.133/2021)', 'ADMINISTRATIVO');

INSERT INTO fluxo_etapa (tipo_processo_id, ordem, unidade_id, acao, prazo_dias, obrigatoria) VALUES
  (1, 1, 3, 'Autoria e apresentação da proposição', 0, 1),
  (1, 2, 40, 'Protocolo, autuação e numeração', 2, 1),
  (1, 3, 9, 'Análise de constitucionalidade e técnica legislativa', 10, 1),
  (1, 4, 21, 'Distribuição às comissões e coleta de pareceres', 15, 1),
  (1, 5, 12, 'Inclusão em Ordem do Dia e deliberação', 5, 1),
  (1, 6, 37, 'Redação final do autógrafo', 3, 1),
  (1, 7, 2, 'Promulgação ou encaminhamento à sanção', 5, 1),
  (2, 1, 40, 'Protocolo e autuação do pedido', 2, 1),
  (2, 2, 17, 'Autorização da despesa', 3, 1),
  (2, 3, 32, 'Termo de referência e pesquisa de preços', 10, 1),
  (2, 4, 14, 'Parecer jurídico prévio', 7, 1),
  (2, 5, 4, 'Condução do certame licitatório', 30, 1),
  (2, 6, 30, 'Homologação e formalização do contrato', 5, 1),
  (2, 7, 27, 'Empenho da despesa', 3, 1),
  (2, 8, 36, 'Publicação do extrato', 2, 1);

INSERT INTO unidade_area (unidade_id, area) VALUES
  (2, 'LEGISLATIVO'),
  (1, 'LEGISLATIVO'),
  (40, 'PROTOCOLO'),
  (38, 'PESSOAL'),
  (38, 'FOLHA'),
  (42, 'FOLHA'),
  (27, 'FOLHA'),
  (29, 'FOLHA'),
  (4, 'COMPRAS'),
  (30, 'COMPRAS'),
  (32, 'COMPRAS'),
  (25, 'COMPRAS'),
  (10, 'CONTROLE'),
  (10, 'FOLHA'),
  (36, 'TRANSPARENCIA'),
  (36, 'CONTROLE'),
  (12, 'LEGISLATIVO'),
  (22, 'LEGISLATIVO'),
  (23, 'LEGISLATIVO'),
  (24, 'LEGISLATIVO'),
  (21, 'LEGISLATIVO'),
  (39, 'USUARIOS'),
  (50, 'LEGISLATIVO'),
  (51, 'LEGISLATIVO'),
  (52, 'LEGISLATIVO'),
  (53, 'LEGISLATIVO'),
  (54, 'LEGISLATIVO'),
  (55, 'LEGISLATIVO'),
  (56, 'LEGISLATIVO'),
  (57, 'LEGISLATIVO'),
  (58, 'LEGISLATIVO'),
  (59, 'LEGISLATIVO'),
  (60, 'LEGISLATIVO'),
  (61, 'LEGISLATIVO'),
  (62, 'LEGISLATIVO'),
  (63, 'LEGISLATIVO'),
  (64, 'LEGISLATIVO'),
  (65, 'LEGISLATIVO'),
  (66, 'LEGISLATIVO'),
  (67, 'LEGISLATIVO'),
  (68, 'LEGISLATIVO'),
  (69, 'LEGISLATIVO'),
  (70, 'LEGISLATIVO'),
  (71, 'LEGISLATIVO'),
  (72, 'LEGISLATIVO'),
  (73, 'LEGISLATIVO'),
  (74, 'LEGISLATIVO'),
  (75, 'LEGISLATIVO'),
  (76, 'LEGISLATIVO'),
  (77, 'LEGISLATIVO'),
  (78, 'LEGISLATIVO');

INSERT INTO unidade_acao (unidade_id, acao) VALUES
  (2, 'CONVOCAR_SESSAO'),
  (2, 'PAUTAR'),
  (2, 'DISTRIBUIR_RELATORIA'),
  (1, 'CONVOCAR_SESSAO'),
  (1, 'APRESENTAR_PROPOSICAO'),
  (1, 'DISTRIBUIR_RELATORIA'),
  (12, 'PAUTAR'),
  (50, 'APRESENTAR_PROPOSICAO'),
  (51, 'APRESENTAR_PROPOSICAO'),
  (52, 'APRESENTAR_PROPOSICAO'),
  (53, 'APRESENTAR_PROPOSICAO'),
  (54, 'APRESENTAR_PROPOSICAO'),
  (55, 'APRESENTAR_PROPOSICAO'),
  (56, 'APRESENTAR_PROPOSICAO'),
  (57, 'APRESENTAR_PROPOSICAO'),
  (58, 'APRESENTAR_PROPOSICAO'),
  (59, 'APRESENTAR_PROPOSICAO'),
  (60, 'APRESENTAR_PROPOSICAO'),
  (61, 'APRESENTAR_PROPOSICAO'),
  (62, 'APRESENTAR_PROPOSICAO'),
  (63, 'APRESENTAR_PROPOSICAO'),
  (64, 'APRESENTAR_PROPOSICAO'),
  (65, 'APRESENTAR_PROPOSICAO'),
  (66, 'APRESENTAR_PROPOSICAO'),
  (67, 'APRESENTAR_PROPOSICAO'),
  (68, 'APRESENTAR_PROPOSICAO'),
  (69, 'APRESENTAR_PROPOSICAO'),
  (70, 'APRESENTAR_PROPOSICAO'),
  (71, 'APRESENTAR_PROPOSICAO'),
  (72, 'APRESENTAR_PROPOSICAO'),
  (73, 'APRESENTAR_PROPOSICAO'),
  (74, 'APRESENTAR_PROPOSICAO'),
  (75, 'APRESENTAR_PROPOSICAO'),
  (76, 'APRESENTAR_PROPOSICAO'),
  (77, 'APRESENTAR_PROPOSICAO'),
  (78, 'APRESENTAR_PROPOSICAO');

